version: '3'
services:
    db-redis:
        container_name: db-redis
        image: 'redis:alpine'
        restart: always
        environment:
            - REDIS_PORT=6379
        ports:
            - "6379:6379"
        command: redis-server --requirepass secret   
    