version: '3'
services:
     db-pgsql:
        container_name: db-pgsql
        image: 'postgres:12'
        restart: always
        environment:
            - POSTGRES_USER=teleb0t
            - POSTGRES_PASSWORD=t0belet
            - POSTGRES_DB=bot
        ports:
            - "5432:5432"
        volumes:
            - '/etc/timezone:/etc/timezone:ro'
            - '/etc/localtime:/etc/localtime:ro'
            - '/var/lib/postgresql:/var/lib/postgresql'
     
